apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rh-hanabi-conventions
  namespace: aiml-reid-research
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10
  storageClassName: longhorn

